In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("GlobalWeatherRepository.csv")

In [4]:
df.head(10)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,05:36 AM,06:32 PM,01:05 PM,01:14 AM,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45,8.0,46.4,Clear,...,4.0,5.3,1,1,07:43 AM,05:59 PM,02:36 PM,01:04 AM,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,2024-05-16 12:45,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,05:45 AM,08:12 PM,01:17 PM,02:31 AM,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,2024-05-16 18:45,9.0,48.2,Clear,...,3.7,5.4,1,1,06:52 AM,05:07 PM,01:31 PM,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,2024-05-16 10:45,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,05:14 AM,08:29 PM,01:00 PM,02:42 AM,Waxing Gibbous,55

In [5]:
df.shape

(109913, 41)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109913 entries, 0 to 109912
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       109913 non-null  object
 1   location_name                 109913 non-null  object
 2   latitude                      109913 non-null  float64
 3   longitude                     109913 non-null  float64
 4   timezone                      109913 non-null  object
 5   last_updated_epoch            109913 non-null  int64
 6   last_updated                  109913 non-null  object
 7   temperature_celsius           109913 non-null  float64
 8   temperature_fahrenheit        109913 non-null  float64
 9   condition_text                109913 non-null  object
 10  wind_mph                      109913 non-null  float64
 11  wind_kph                      109913 non-null  float64
 12  wind_degree                   109913 non-null  int64
 13  wind_direction                109913 non-null  object
 14  pressure_mb                   109913 non-null  float64
 15  pressure_in                   109913 non-null  float64
 16  precip_mm                     109913 non-null  float64
 17  precip_in                     109913 non-null  float64
 18  humidity                      109913 non-null  int64
 19  cloud                         109913 non-null  int64
 20  feels_like_celsius            109913 non-null  float64
 21  feels_like_fahrenheit         109913 non-null  float64
 22  visibility_km                 109913 non-null  float64
 23  visibility_miles              109913 non-null  float64
 24  uv_index                      109913 non-null  float64
 25  gust_mph                      109913 non-null  float64
 26  gust_kph                      109913 non-null  float64
 27  air_quality_Carbon_Monoxide   109913 non-null  float64
 28  air_quality_Ozone             109913 non-null  float64
 29  air_quality_Nitrogen_dioxide  109913 non-null  float64
 30  air_quality_Sulphur_dioxide   109913 non-null  float64
 31  air_quality_PM2.5             109913 non-null  float64
 32  air_quality_PM10              109913 non-null  float64
 33  air_quality_us-epa-index      109913 non-null  int64
 34  air_quality_gb-defra-index    109913 non-null  int64
 35  sunrise                       109913 non-null  object
 36  sunset                        109913 non-null  object
 37  moonrise                      109913 non-null  object
 38  moonset                       109913 non-null  object
 39  moon_phase                    109913 non-null  object
 40  moon_illumination             109913 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 34.4+ MB

In [7]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [9]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,109913.000000,109913.000000,1.099130e+05,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,...,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000,109913.000000
mean,19.173198,22.032499,1.740312e+09,22.425950,72.368465,8.130166,13.087711,170.504936,1014.046200,29.944121,...,18.328138,496.198246,60.852648,15.553002,10.904686,25.145427,50.785095,1.726884,2.675853,49.556850
std,24.440948,65.799993,1.411387e+07,8.947118,16.104639,7.604636,12.235756,102.853033,10.944347,0.323139,...,14.280653,814.121696,31.697642,25.203634,38.743428,39.179443,156.945076,0.962676,2.507089,35.013388
min,-41.300000,-175.200000,1.715849e+09,-24.900000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.728121e+09,17.300000,63.100000,4.000000,6.500000,82.000000,1010.000000,29.830000,...,10.400000,223.600000,40.000000,1.480000,0.925000,7.215000,10.360000,1.000000,1.000000,15.000000
50%,17.250000,23.316700,1.740306e+09,24.400000,75.900000,6.900000,11.200000,164.000000,1013.000000,29.930000,...,15.600000,314.500000,58.000000,5.180000,2.405000,14.615000,20.905000,1.000000,2.000000,49.000000
75%,40.400000,50.580000,1.752569e+09,28.200000,82.800000,11.200000,18.000000,256.000000,1018.000000,30.060000,...,24.200000,490.250000,77.000000,17.894000,8.850000,28.650000,43.475000,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.764660e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [25]:
df[["country", "location_name", "temperature_celsius", "temperature_fahrenheit", "wind_mph", "wind_kph", "wind_degree", "wind_direction", "pressure_mb", "pressure_in", "precip_mm", "precip_in", "humidity", "feels_like_celsius", "feels_like_fahrenheit"]]

,country,location_name,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,feels_like_celsius,feels_like_fahrenheit
0,Afghanistan,Kabul,26.6,79.8,8.3,13.3,338,NNW,1012.0,29.89,0.00,0.00,24,25.3,77.5
1,Albania,Tirana,19.0,66.2,6.9,11.2,320,NW,1012.0,29.88,0.10,0.00,94,19.0,66.2
2,Algeria,Algiers,23.0,73.4,9.4,15.1,280,W,1011.0,29.85,0.00,0.00,29,24.6,76.4
3,Andorra,Andorra La Vella,6.3,43.3,7.4,11.9,215,SW,1007.0,29.75,0.30,0.01,61,3.8,38.9
4,Angola,Luanda,26.0,78.8,8.1,13.0,150,SSE,1011.0,29.85,0.00,0.00,89,28.7,83.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109908,Venezuela,Caracas,26.0,78.8,2.2,3.6,155,SSE,1010.0,29.83,0.00,0.00,79,30.0,86.1
109909,Vietnam,Hanoi,27.1,80.8,2.9,4.7,354,N,1011.0,29.85,0.00,0.00,62,29.6,85.2
109910,Yemen,Sanaa,15.3,59.6,2.2,3.6,83,E,1018.0,30.08,0.00,0.00,13,15.3,59.6
109911,Zambia,Lusaka,24.5,76.1,6.7,10.8,62,ENE,1012.0,29.88,0.84,0.03,59,25.8,78.4
109912,Zimbabwe,Harare,22.1,71.8,10.5,16.9,38,NE,1013.0,29.93,0.75,0.03,64,24.6,76.3

In [11]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [12]:
df["timezone"]

0              Asia/Kabul
1           Europe/Tirane
2          Africa/Algiers
3          Europe/Andorra
4           Africa/Luanda
               ...
109908    America/Caracas
109909       Asia/Bangkok
109910          Asia/Aden
109911      Africa/Lusaka
109912      Africa/Harare
Name: timezone, Length: 109913, dtype: object

In [13]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
109908    False
109909    False
109910    False
109911    False
109912    False
Length: 109913, dtype: bool

In [33]:
datatye = df[df["country"].str.contains("India", case=False, na=False)]

In [26]:
df[["country", "location_name", "temperature_celsius", "temperature_fahrenheit", "wind_mph", "wind_kph", "wind_degree", "wind_direction", "pressure_mb", "pressure_in", "precip_mm", "precip_in", "humidity", "feels_like_celsius", "feels_like_fahrenheit"]]

,country,location_name,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,feels_like_celsius,feels_like_fahrenheit
0,Afghanistan,Kabul,26.6,79.8,8.3,13.3,338,NNW,1012.0,29.89,0.00,0.00,24,25.3,77.5
1,Albania,Tirana,19.0,66.2,6.9,11.2,320,NW,1012.0,29.88,0.10,0.00,94,19.0,66.2
2,Algeria,Algiers,23.0,73.4,9.4,15.1,280,W,1011.0,29.85,0.00,0.00,29,24.6,76.4
3,Andorra,Andorra La Vella,6.3,43.3,7.4,11.9,215,SW,1007.0,29.75,0.30,0.01,61,3.8,38.9
4,Angola,Luanda,26.0,78.8,8.1,13.0,150,SSE,1011.0,29.85,0.00,0.00,89,28.7,83.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109908,Venezuela,Caracas,26.0,78.8,2.2,3.6,155,SSE,1010.0,29.83,0.00,0.00,79,30.0,86.1
109909,Vietnam,Hanoi,27.1,80.8,2.9,4.7,354,N,1011.0,29.85,0.00,0.00,62,29.6,85.2
109910,Yemen,Sanaa,15.3,59.6,2.2,3.6,83,E,1018.0,30.08,0.00,0.00,13,15.3,59.6
109911,Zambia,Lusaka,24.5,76.1,6.7,10.8,62,ENE,1012.0,29.88,0.84,0.03,59,25.8,78.4
109912,Zimbabwe,Harare,22.1,71.8,10.5,16.9,38,NE,1013.0,29.93,0.75,0.03,64,24.6,76.3

In [31]:
high_humidity = df.query("humidity > 60")

In [32]:
high_humidity

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.1200,-61.8500,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.20,4.50,1,1,05:36 AM,06:32 PM,01:05 PM,01:14 AM,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.5900,-58.6700,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45,8.0,46.4,Clear,...,4.00,5.30,1,1,07:43 AM,05:59 PM,02:36 PM,01:04 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109905,Uruguay,Montevideo,-34.8581,-56.1708,America/Montevideo,1764659700,2025-12-02 04:15,14.2,57.6,Fog,...,6.45,8.55,1,1,05:24 AM,07:45 PM,05:21 PM,03:07 AM,Waxing Gibbous,88
109907,Vanuatu,Port Vila,-17.7333,168.3167,Pacific/Efate,1764659700,2025-12-02 18:15,28.2,82.8,Partly cloudy,...,6.45,9.45,1,1,05:03 AM,06:10 PM,03:11 PM,02:07 AM,Waxing Gibbous,83
109908,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1764659700,2025-12-02 03:15,26.0,78.8,Mist,...,8.65,10.15,1,1,06:30 AM,06:04 PM,03:53 PM,03:51 AM,Waxing Gibbous,88
109909,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1764659700,2025-12-02 14:15,27.1,80.8,Mist,...,127.05,127.05,4,10,06:17 AM,05:14 PM,02:43 PM,03:03 AM,Waxing Gibbous,85
109912,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1764659700,2025-12-02 09:15,22.1,71.8,Patchy rain nearby,...,12.95,13.05,1,2,05:12 AM,06:19 PM,03:45 PM,02:32 AM,Waxing Gibbous,86

In [37]:
india_df = df[df["country"].str.contains("India", case=False, na=False)]

In [42]:
india_df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
77,India,New Delhi,28.6,77.2,Asia/Kolkata,1715849100,2024-05-16 14:15,42.0,107.6,Mist,...,25.40,64.00,2,3,05:30 AM,07:06 PM,12:47 PM,01:30 AM,Waxing Gibbous,55
272,India,New Delhi,28.6,77.2,Asia/Kolkata,1715868000,2024-05-16 19:30,38.0,100.4,Mist,...,44.00,80.80,3,5,05:30 AM,07:06 PM,12:47 PM,01:30 AM,Waxing Gibbous,55
467,India,New Delhi,28.6,77.2,Asia/Kolkata,1715961600,2024-05-17 21:30,36.0,96.8,Mist,...,49.70,83.70,3,6,05:30 AM,07:06 PM,01:40 PM,01:58 AM,Waxing Gibbous,64
659,India,New Delhi,28.6,77.2,Asia/Kolkata,1716042600,2024-05-18 20:00,41.0,105.8,Mist,...,32.50,58.70,2,3,05:29 AM,07:07 PM,02:32 PM,02:24 AM,Waxing Gibbous,73
853,India,New Delhi,28.6,77.2,Asia/Kolkata,1716128100,2024-05-19 19:45,41.0,105.8,Mist,...,31.70,55.00,2,3,05:28 AM,07:08 PM,03:24 PM,02:51 AM,Waxing Gibbous,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109015,India,New Delhi,28.6,77.2,Asia/Kolkata,1764315000,2025-11-28 13:00,23.2,73.8,Mist,...,118.85,119.55,4,10,06:54 AM,05:24 PM,12:47 PM,No moonset,First Quarter,45
109210,India,New Delhi,28.6,77.2,Asia/Kolkata,1764399600,2025-11-29 12:30,23.1,73.6,Mist,...,79.35,80.05,4,10,06:55 AM,05:24 PM,01:18 PM,12:31 AM,Waxing Gibbous,55
109405,India,New Delhi,28.6,77.2,Asia/Kolkata,1764485100,2025-11-30 12:15,20.2,68.4,Mist,...,73.05,73.45,4,10,06:56 AM,05:24 PM,01:50 PM,01:32 AM,Waxing Gibbous,66
109600,India,New Delhi,28.6,77.2,Asia/Kolkata,1764574200,2025-12-01 13:00,23.2,73.8,Mist,...,142.85,142.85,4,10,06:56 AM,05:24 PM,02:23 PM,02:35 AM,Waxing Gibbous,76
109795,India,New Delhi,28.6,77.2,Asia/Kolkata,1764659700,2025-12-02 12:45,24.2,75.6,Mist,...,154.05,154.95,5,10,06:57 AM,05:24 PM,03:00 PM,03:42 AM,Waxing Gibbous,85

In [44]:
india_humidity = india_df[india_df["humidity"] > 60]

In [46]:
india_temp = india_df[(india_df["temperature_celsius"] <= 0) | (india_df["temperature_celsius"] < 15)]

In [47]:
india_temp

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
42791,India,New Delhi,28.6,77.2,Asia/Kolkata,1734950700,2024-12-23 16:15,14.3,57.8,Patchy rain nearby,...,257.520,260.110,6,10,07:11 AM,05:30 PM,12:13 AM,12:26 PM,Last Quarter,52
45520,India,New Delhi,28.6,77.2,Asia/Kolkata,1736159400,2025-01-06 16:00,14.4,57.9,Fog,...,219.225,222.185,5,10,07:15 AM,05:40 PM,11:34 AM,No moonset,Waxing Crescent,36
46459,India,New Delhi,28.6,77.2,Asia/Kolkata,1736591400,2025-01-11 16:00,14.3,57.7,Moderate or heavy rain with thunder,...,269.730,273.060,6,10,07:15 AM,05:43 PM,03:00 PM,04:46 AM,Waxing Gibbous,88

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 4, 5, 'Nobita'])
arr

array(['1', '2', '4', '5', 'Nobita'], dtype='<U21')

In [3]:
arr2D = np.array([[1, 3, 5, 3], [4, 2, 9, 0], [4, 6, 9, 6]])
arr2D

array([[1, 3, 5, 3],
       [4, 2, 9, 0],
       [4, 6, 9, 6]])

In [7]:
arr3 = np.zeros((2, 3))
arr3

arr4 = np.ones((2, 3))
arr4

arr5 = np.eye((4))
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
import pandas as pd

index = 0

my_list = [10, 20, 30, 40, 50]
my_series = pd.Series(my_list)

while index < len(my_series):
    print(my_series[index])
    index += 1

10
20
30
40
50

In [14]:
import pandas as pd

my_mixed_list = [10, 'apple', 20, 'banana', 30]

my_mixed_series = pd.Series(my_mixed_list)

print(my_mixed_series)

0        10
1     apple
2        20
3    banana
4        30
dtype: object

In [ ]:

import pandas as pd

# Create two Pandas Series
names_series = pd.Series(['Alice', 'Bob', 'Charlie', 'David'])
ages_series = pd.Series([25, 30, 22, 35])

# Create a dictionary where keys are column names and values are the Series
data_dict = {'Name': names_series, 'Age': ages_series}

# Create a DataFrame from the dictionary of Series and print it
df = pd.DataFrame(data_dict)

In [17]:

import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}

df = pd.DataFrame(data)

df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [20]:
# Create a Pandas Series using the list [100, 200, 300] with index labels ['a', 'b', 'c'].
data = pd.Series([100, 200, 300], index= ['a', 'b', 'c'])
print(data)

a    100
b    200
c    300
dtype: int64

In [25]:
# Q2. Access Elements from Series
s = pd.Series([5, 10, 15, 20])

print(s.iloc[0])
print(s.iloc[-1])

5
20

In [27]:
# Q3. Series from Dictionary, Create a Pandas Series from the dictionary:
my_dict = {'Math': 85, 'Science': 90, 'English': 88}

convert_series = pd.Series(my_dict)
print(convert_series)

Math       85
Science    90
English    88
dtype: int64

In [34]:
import pandas as pd
import numpy as np

In [36]:
df = pd.DataFrame(np.random.randint(1, 100, size=(3, 4)),
                    columns = ['A', 'B', 'C', 'D']
                 )
row_sum = []

for i in range(len(df)):
    total = 0
    for value in df.iloc[i]:
        total += value
    row_sum.append(total)
df['Row_Sum'] = row_sum

In [37]:
df

    A   B   C   D  Row_Sum
0   9  21  32  42      104
1  73  23  20  74      190
2  93  61  85  40      279

In [45]:
df = pd.DataFrame(np.random.randint(1, 100, size=(3, 4)),
                    columns = ['A', 'B', 'C', 'D']
                 )
df

row_sum = []

for i in range(len(df)):
    total = 0
    for value in df.iloc[i]:
        total += value
    row_sum.append(total)
df['Row_Sum'] = row_sum

In [47]:
df['Marks'] = np.random.randint(1, 100)

In [50]:
df

    A   B   C   D  Row_Sum  Marks
0  12   2  98  89      201     43
1  79  81  23  53      236     43
2  10  58  37  71      176     43