In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\nobita\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nobita\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nobita\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nobita\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nobita\anaconda3\lib\site-packages (from requests) (2025.11.12)

In [2]:
import requests

In [3]:
URL = "https://stephen-king-api.onrender.com/api/books"

In [6]:
requests.get(URL)

In [7]:
res = requests.get(URL)

In [9]:
json_data = res.json()

In [12]:
# Get the json() data
json_data

AttributeError: 'dict' object has no attribute 'head'

In [13]:
import pandas as pd

In [18]:
df = pd.json_normalize(json_data["data"])
df.head()

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."

In [19]:
df.isnull().sum()

id            0
Year          0
Title         0
handle        0
Publisher     0
ISBN          0
Pages         0
Notes         0
created_at    0
villains      0
dtype: int64

# Web Scraping

In [20]:
import requests

In [21]:
URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)

In [22]:
res

In [23]:
# CHECK THE STATUS CODE:
print(res.status_code)

200

In [26]:
if res.status_code == 200:
    # print(res.text)
    # print(res.content)
    print(res.headers)
    
else:
    print("Status not OK...")

{'Date': 'Sat, 13 Dec 2025 10:30:42 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=r75HwES%2BONKoyjexA%2FFOx8ouutg9tE07BHMh9f8zmrc%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1765621842"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=r75HwES%2BONKoyjexA%2FFOx8ouutg9tE07BHMh9f8zmrc%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1765621842"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9ad4c9a07f2b3c3a-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [28]:
# ALL HTML DATA STORED IN THE WITHN THE FILE
with open("scrapped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

# Beautifull Soup4

In [29]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\nobita\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\nobita\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

In [33]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\nobita\anaconda3\lib\site-packages (5.3.0)

In [34]:
from bs4 import BeautifulSoup

In [37]:
# OPEN SCRAPPED FILE
with open('scrapped_data/data1.html', 'r') as f:
    html_content = f.read()

# CALL THE SOUP OBJECT
soup = BeautifulSoup(html_content, 'lxml') # lxml ---> lxml is a fast Python library used to parse and process HTML and XML documents.

In [39]:
#soup # print all data

In [42]:
# METHODS: 
# 1. find() - print 1st matching element
soup.find('h1')
soup.find('h3') # means that print the first 1st h3 tag element on website.
soup.h3 # Direct access

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [46]:
# 2. find_all() --> print all matching elements
#soup.find_all('h3') # print here all h3 tag elements

In [64]:
all_h3 = soup.find_all('h3')

# Get all country name using the FOR LOOP:
for h3 in all_h3:
    # print(h3.get_text(strip=True))

    # Stored in the name veriable
    name  = h3.get_text(strip=True)

    # Print the Parent elements
    # print(h3.find_parent('div')['class'])

    # Print the neighbour element - select ()
    population = h3.find_next('div').select('span.country-population')[0].get_text(strip=True)

    # select_one()
    print(h3.find_next('div').select_one('span.country-population').get_text(strip=True))

    print(h3.attrs)

84000
{'class': ['country-name']}
4975593
{'class': ['country-name']}
29121286
{'class': ['country-name']}
86754
{'class': ['country-name']}
13254
{'class': ['country-name']}
2986952
{'class': ['country-name']}
2968000
{'class': ['country-name']}
13068161
{'class': ['country-name']}
0
{'class': ['country-name']}
41343201
{'class': ['country-name']}
57881
{'class': ['country-name']}
8205000
{'class': ['country-name']}
21515754
{'class': ['country-name']}
71566
{'class': ['country-name']}
26711
{'class': ['country-name']}
8303512
{'class': ['country-name']}
4590000
{'class': ['country-name']}
285653
{'class': ['country-name']}
156118464
{'class': ['country-name']}
10403000
{'class': ['country-name']}
16241811
{'class': ['country-name']}
7148785
{'class': ['country-name']}
738004
{'class': ['country-name']}
9863117
{'class': ['country-name']}
9056010
{'class': ['country-name']}
8450
{'class': ['country-name']}
65365
{'class': ['country-name']}
395027
{'class': ['country-name']}
9947418
{'class': ['country-name']}
18012
{'class': ['country-name']}
201103330
{'class': ['country-name']}
301790
{'class': ['country-name']}
699847
{'class': ['country-name']}
0
{'class': ['country-name']}
2029307
{'class': ['country-name']}
9685000
{'class': ['country-name']}
314522
{'class': ['country-name']}
33679000
{'class': ['country-name']}
628
{'class': ['country-name']}
70916439
{'class': ['country-name']}
4844927
{'class': ['country-name']}
3039126
{'class': ['country-name']}
7581000
{'class': ['country-name']}
21058798
{'class': ['country-name']}
21388
{'class': ['country-name']}
16746491
{'class': ['country-name']}
19294149
{'class': ['country-name']}
1330044000
{'class': ['country-name']}
47790000
{'class': ['country-name']}
4516220
{'class': ['country-name']}
11423000
{'class': ['country-name']}
508659
{'class': ['country-name']}
141766
{'class': ['country-name']}
1500
{'class': ['country-name']}
1102677
{'class': ['country-name']}
10476000
{'class': ['country-name']}
81802257
{'class': ['country-name']}
740528
{'class': ['country-name']}
5484000
{'class': ['country-name']}
72813
{'class': ['country-name']}
9823821
{'class': ['country-name']}
34586184
{'class': ['country-name']}
14790608
{'class': ['country-name']}
1291170
{'class': ['country-name']}
80471869
{'class': ['country-name']}
273008
{'class': ['country-name']}
5792984
{'class': ['country-name']}
46505963
{'class': ['country-name']}
88013491
{'class': ['country-name']}
5244000
{'class': ['country-name']}
875983
{'class': ['country-name']}
2638
{'class': ['country-name']}
107708
{'class': ['country-name']}
48228
{'class': ['country-name']}
64768389
{'class': ['country-name']}
1545255
{'class': ['country-name']}
62348447
{'class': ['country-name']}
107818
{'class': ['country-name']}
4630000
{'class': ['country-name']}
195506
{'class': ['country-name']}
65228
{'class': ['country-name']}
24339838
{'class': ['country-name']}
27884
{'class': ['country-name']}
56375
{'class': ['country-name']}
1593256
{'class': ['country-name']}
10324025
{'class': ['country-name']}
443000
{'class': ['country-name']}
1014999
{'class': ['country-name']}
11000000
{'class': ['country-name']}
30
{'class': ['country-name']}
13550440
{'class': ['country-name']}
159358
{'class': ['country-name']}
1565126
{'class': ['country-name']}
748486
{'class': ['country-name']}
6898686
{'class': ['country-name']}
0
{'class': ['country-name']}
7989415
{'class': ['country-name']}
4491000
{'class': ['country-name']}
9648924
{'class': ['country-name']}
9982000
{'class': ['country-name']}
242968342
{'class': ['country-name']}
4622917
{'class': ['country-name']}
7353985
{'class': ['country-name']}
75049
{'class': ['country-name']}
1173108018
{'class': ['country-name']}
4000
{'class': ['country-name']}
29671605
{'class': ['country-name']}
76923300
{'class': ['country-name']}
308910
{'class': ['country-name']}
60340328
{'class': ['country-name']}
90812
{'class': ['country-name']}
2847232
{'class': ['country-name']}
6407085
{'class': ['country-name']}
127288000
{'class': ['country-name']}
40046566
{'class': ['country-name']}
5776500
{'class': ['country-name']}
14453680
{'class': ['country-name']}
92533
{'class': ['country-name']}
773407
{'class': ['country-name']}
51134
{'class': ['country-name']}
22912177
{'class': ['country-name']}
48422644
{'class': ['country-name']}
2789132
{'class': ['country-name']}
44270
{'class': ['country-name']}
15340000
{'class': ['country-name']}
6368162
{'class': ['country-name']}
4125247
{'class': ['country-name']}
160922
{'class': ['country-name']}
35000
{'class': ['country-name']}
21513990
{'class': ['country-name']}
3685076
{'class': ['country-name']}
1919552
{'class': ['country-name']}
2944459
{'class': ['country-name']}
497538
{'class': ['country-name']}
2217969
{'class': ['country-name']}
6461454
{'class': ['country-name']}
31627428
{'class': ['country-name']}
32965
{'class': ['country-name']}
4324000
{'class': ['country-name']}
666730
{'class': ['country-name']}
35925
{'class': ['country-name']}
21281844
{'class': ['country-name']}
65859
{'class': ['country-name']}
2062294
{'class': ['country-name']}
13796354
{'class': ['country-name']}
53414374
{'class': ['country-name']}
3086918
{'class': ['country-name']}
449198
{'class': ['country-name']}
53883
{'class': ['country-name']}
432900
{'class': ['country-name']}
3205060
{'class': ['country-name']}
9341
{'class': ['country-name']}
403000
{'class': ['country-name']}
1294104
{'class': ['country-name']}
395650
{'class': ['country-name']}
15447500
{'class': ['country-name']}
112468855
{'class': ['country-name']}
28274729
{'class': ['country-name']}
22061451
{'class': ['country-name']}
2128471
{'class': ['country-name']}
216494
{'class': ['country-name']}
15878271
{'class': ['country-name']}
1828
{'class': ['country-name']}
154000000
{'class': ['country-name']}
5995928
{'class': ['country-name']}
16645000
{'class': ['country-name']}
5009150
{'class': ['country-name']}
28951852
{'class': ['country-name']}
10065
{'class': ['country-name']}
2166
{'class': ['country-name']}
4252277
{'class': ['country-name']}
2967717
{'class': ['country-name']}
3410676
{'class': ['country-name']}
29907003
{'class': ['country-name']}
270485
{'class': ['country-name']}
6064515
{'class': ['country-name']}
99900177
{'class': ['country-name']}
184404791
{'class': ['country-name']}
38500000
{'class': ['country-name']}
7012
{'class': ['country-name']}
46
{'class': ['country-name']}
3916632
{'class': ['country-name']}
3800000
{'class': ['country-name']}
10676000
{'class': ['country-name']}
19907
{'class': ['country-name']}
6375830
{'class': ['country-name']}
840926
{'class': ['country-name']}
776948
{'class': ['country-name']}
21959278
{'class': ['country-name']}
7344847
{'class': ['country-name']}
140702000
{'class': ['country-name']}
11055976
{'class': ['country-name']}
25731776
{'class': ['country-name']}
559198
{'class': ['country-name']}
88340
{'class': ['country-name']}
35000000
{'class': ['country-name']}
9828655
{'class': ['country-name']}
4701069
{'class': ['country-name']}
7460
{'class': ['country-name']}
2007000
{'class': ['country-name']}
2550
{'class': ['country-name']}
5455000
{'class': ['country-name']}
5245695
{'class': ['country-name']}
31477
{'class': ['country-name']}
12323252
{'class': ['country-name']}
10112453
{'class': ['country-name']}
492829
{'class': ['country-name']}
8260490
{'class': ['country-name']}
175808
{'class': ['country-name']}
6052064
{'class': ['country-name']}
37429
{'class': ['country-name']}
22198110
{'class': ['country-name']}
1354051
{'class': ['country-name']}
20556
{'class': ['country-name']}
10543464
{'class': ['country-name']}
140
{'class': ['country-name']}
6587239
{'class': ['country-name']}
67089500
{'class': ['country-name']}
7487489
{'class': ['country-name']}
1466
{'class': ['country-name']}
1154625
{'class': ['country-name']}
4940916
{'class': ['country-name']}
10589025
{'class': ['country-name']}
122580
{'class': ['country-name']}
77804122
{'class': ['country-name']}
1228691
{'class': ['country-name']}
10472
{'class': ['country-name']}
22894384
{'class': ['country-name']}
41892895
{'class': ['country-name']}
45415596
{'class': ['country-name']}
33398682
{'class': ['country-name']}
0
{'class': ['country-name']}
310232863
{'class': ['country-name']}
3477000
{'class': ['country-name']}
27865738
{'class': ['country-name']}
921
{'class': ['country-name']}
104217
{'class': ['country-name']}
27223228
{'class': ['country-name']}
21730
{'class': ['country-name']}
108708
{'class': ['country-name']}
89571130
{'class': ['country-name']}
221552
{'class': ['country-name']}
16025
{'class': ['country-name']}
192001
{'class': ['country-name']}
1800000
{'class': ['country-name']}
23495361
{'class': ['country-name']}
159042
{'class': ['country-name']}
49000000
{'class': ['country-name']}
13460305
{'class': ['country-name']}
11651858
{'class': ['country-name']}

In [68]:
all_h3 = soup.find_all('h3')

all_countries = []

# Get all country name using the FOR LOOP:
for h3 in all_h3:
    # print(h3.get_text(strip=True))

    # Stored in the name veriable
    name  = h3.get_text(strip=True)

    # Print the Parent elements
    # print(h3.find_parent('div')['class'])

    # Print the neighbour element - select ()
    population = h3.find_next('div').select('span.country-population')[0].get_text(strip=True)

    # select_one()
    # print(h3.find_next('div').select_one('span.country-population').get_text(strip=True))

    # print(h3.attrs)

    all_countries.append([name, population])

In [80]:
all_countries

# CONVERT THESE DATA INTO THE DATAFRAME
import pandas as pd

df = pd.DataFrame(all_countries, columns=['Name', 'Populations'])

In [78]:
df.head()

                   Name Populations
0               Andorra       84000
1  United Arab Emirates     4975593
2           Afghanistan    29121286
3   Antigua and Barbuda       86754
4              Anguilla       13254

In [83]:
# STORE THE DATA INTO THE CSV FILE
df.to_csv("cleaned_data/data.csv", index=False)

In [84]:
df.to_csv("cleaned_data/data1.csv")

In [85]:
# DOM ---> parent, children, descendants, next_sibiling(), previous_sibiling()

print(h3.parent)

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-zw"></i>
                            Zimbabwe
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Harare</span><br/>
<strong>Population:</strong> <span class="country-population">11651858</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">390580.0</span><br/>
</div>
</div>