In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("powerplant_data.csv")

In [3]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
# AT => Temperature
# VT => vacuum
# AP => Pressure
# RH => Humidity

# PE => Produced Energy

In [5]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [6]:
X = df.drop("PE", axis=1)
y = df["PE"]

In [7]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [8]:
y.head()

0    480.48
1    445.75
2    438.76
3    453.09
4    464.43
Name: PE, dtype: float64

## STEPS FOR IMPLEMENTING THE ANN FOP REGRESSION
- Load the data
- Data --> Tensors
- Tensor Dataset & DataLoader
- Define ANN model
- Train the Model
- save the model
- Evaluate

In [9]:
# SPLIT OUT DATA

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
X_train

         AT      V       AP     RH
5487  25.24  63.47  1011.30  66.21
3522  26.09  70.40  1007.41  85.37
6916  26.63  73.68  1015.15  85.13
7544  32.06  71.85  1007.90  56.44
7600  28.70  71.64  1007.11  69.85
...     ...    ...      ...    ...
5734  26.25  61.02  1011.47  71.22
5191  29.17  64.79  1016.43  61.05
5390  18.00  43.70  1015.40  61.28
860   26.73  68.84  1010.75  66.83
7270   6.40  39.18  1024.60  86.83

[7654 rows x 4 columns]

In [15]:
df.shape

(9568, 5)

In [18]:
# SCALING THE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
X_train_scaled

array([[ 0.74805289,  0.72006931, -0.32660017, -0.49711722],
       [ 0.86181948,  1.26515721, -0.98521113,  0.8181501 ],
       [ 0.93409473,  1.52314975,  0.32523844,  0.80167494],
       ...,
       [-0.22097078, -0.834965  ,  0.36756563, -0.83554456],
       [ 0.94747903,  1.14245344, -0.41971997, -0.45455637],
       [-1.77355014, -1.19049131,  1.92520594,  0.91837402]],
      shape=(7654, 4))

In [20]:
X_test_scaled

array([[ 1.34499288,  0.23869298, -1.28658067, -1.10532538],
       [ 0.81095912,  1.36269098, -0.74140656,  0.26485915],
       [-0.2437241 , -0.73900436,  1.99970178, -0.19713193],
       ...,
       [-0.67068342, -1.15902881, -0.29951077, -0.10651852],
       [ 1.31420898,  1.33752097, -0.87346737, -0.44288647],
       [-0.2611237 , -0.27021304,  0.37433797,  1.10646548]],
      shape=(1914, 4))

In [21]:
import torch
import torch.nn as nn

In [25]:
# Convert scaled data into the TENSOR

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)


X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [26]:
type(X_train_scaled)

numpy.ndarray

In [27]:
type(y_train)

pandas.core.series.Series

In [28]:
# TENSOR-DATASET & DATALOADER 
# TENSOR-DATASET SYNTAX -----> TensorDataset(in_features, out_features)

from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [29]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True) # shuffle - DATA COMING SHUFFLE
test_loader = DataLoader(test_dataset, batch_size=32)